# ************** Component CRD **************#
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: components.charity-project.eu
spec:
  scope: Namespaced
  group: charity-project.eu
  names:
    kind: Component
    plural: Components
    singular: Component
    shortNames:
      - comp
      - comps
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                # ************* Adding this field *************#
                app:
                  type: string
                # *********************************************#

                # ************* Removing this field *************#
                # cluster-selector:
                #   type: string
                # *********************************************#

                image:
                  type: string

                #******* Adding replicas field *******#
                replicas:
                  type: integer
                # *********************************#
                expose:
                  type: array
                  items:
                    type: object
                    properties:
                      is-public:
                        type: boolean
                      is-peered:
                        type: boolean
                      #******* Adding this field, if it is set to true a prometheus instance scraping this component will be created *******#
                      is-exposing-metrics:
                        type: boolean
                      # *********************************#
                      containerPort:
                        type: integer
                      clusterPort:
                        type: integer
                env:
                  type: object
                  properties:
                    is-secret:
                      type: boolean
                    variables:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                          value:
                            type: string
                tls:
                  type: object
                  properties:
                    name:
                      type: string
                    # certificate:
                    #   type: string
                    # key:
                    #   type: string
                # registry:
                #   type: object
                #   properties:
                #     repository:
                #       type: string
                #     username:
                #       type: string
                #     password:
                #       type: string
                #     email:
                #       type: string

              #x-kubernetes-validations:
              #- rule: "self.all(x, size(self.filter(e, x.name == e.name)) == 1)"

            # ************************ Status ************************#
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true

      additionalPrinterColumns:
        - name: Current status # Rrunning, pending, Failed
          type: string
          priority: 0
          jsonPath: .status.component_watch.current_status
        - name: Details
          type: object
          priority: 0
          jsonPath: .status.component_watch.details # If status is Running, No details to provide
