apiVersion: v1
kind: Service
metadata:
  name: {component_name}        # Application_2.component, following the example above: node-app
  namespace: {namespace_app_1}  # Application_1.name, following the example above : frontend
spec:
  type: ExternalName
  externalName: "{component_name}.{namespace_app_2}.svc.cluster.local"    # node-app.rest-api.svc.cluster.local
  ports: 
  - port: {port} # following the example above: 4000